"""add favorites table

Revision ID: ad7dabc5db60
Revises: 2eb19dd348ed
Create Date: 2025-03-30 20:05:07.531095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad7dabc5db60'
down_revision: Union[str, None] = '2eb19dd348ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('shanyrak_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shanyrak_id'], ['shanyraks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
