# Generated by Django 5.2 on 2025-04-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_violationlevel_pointreward_violationtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='Учебный год, например: 2024-2025', max_length=9)),
                ('student_full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Мальчик'), ('F', 'Девочка')], max_length=10)),
                ('class_name', models.CharField(max_length=10)),
                ('shanyrak_name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('reward', 'Награда'), ('violation', 'Наказание')], max_length=20)),
                ('from_full_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('points', models.IntegerField()),
                ('violation_type', models.CharField(blank=True, max_length=255, null=True)),
                ('violation_level', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Admin'), (1, 'Teacher'), (2, 'Curator'), (3, 'Vice')]),
        ),
    ]
